# nodejs.yml
name: Node.js CI

on:
  push:
    branches:
      - test_** # Trigger the build on commits to any feature branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm install

      - name: Merge to master
        uses: "peter-evans/create-pull-request@v5"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          title: "Merge feature branch to master"
          body: "Automatically merging feature branch to master"
          labels: "auto-merge"